# Exact same as 'Dockerfile', but we do not start the app.
# Fetch docker image from Docker Hub.
FROM node:14

# Create working directory.
WORKDIR /application

# Copy the 'package.json' and 'package-lock.json' for deterministic builds.
COPY package*.json ./

# Install our application.
RUN npm ci --only=production

# Copy our installed API to our working directory.
COPY . ./
