apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-docker-kubernetes-deployment
  labels:
    app: ndk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ndk
    template:
      metadata:
        labels:
          app: ndk
      spec:
        containers:
          - name: ndk
            image: lauslim12/node-docker-kubernetes
            imagePullPolicy: Always
            ports:
              - containerPort: 3000
