apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-docker-kubernetes-deployment
  labels:
    app: ndk
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ndk
  template:
    metadata:
      labels:
        app: ndk
    spec:
      dnsPolicy: Default
      containers:
        - name: ndk
          image: lauslim12/node-docker-kubernetes:1.0.0
          envFrom:
            - secretRef:
                name: prod-secrets
          ports:
            - containerPort: 3000
