apiVersion: v1
kind: Service
metadata:
  name: ndk
spec:
  selector:
    app: ndk
  type: LoadBalancer
  ports:
    - name: defaultport
      protocol: TCP
      port: 80
      targetPort: 3000
